# Generated by Django 3.1.5 on 2021-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/%Y/%m/%d'),
        ),
    ]
