# Generated by Django 3.0.8 on 2020-11-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название товара')),
                ('cost', models.FloatField(verbose_name='Цена')),
                ('intro', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Полное описание')),
            ],
        ),
    ]
