# Generated by Django 3.1.5 on 2021-05-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210518_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
