# Generated by Django 3.0.8 on 2020-11-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20201115_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, upload_to='items/%Y/%m/%d'),
        ),
    ]
