# Generated by Django 3.1.5 on 2021-01-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='items/%Y/%m/%d'),
        ),
    ]
