# Generated by Django 3.1.5 on 2021-01-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210113_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default='Прочее', max_length=80, verbose_name='Категория'),
        ),
    ]
